/*
	THIS IS A C CODE COMPILED BY C18 COMPILER 
	CREATOR : DALI FETHI ABDELLATIF
	DATE : 27/05/2024
	USING ADC MODULE TO CONVERT AN ANALOG SIGNAL PRESENTS AT THE RA0 PIN TO A DIGITAL VALUE 
	THE VDD VOLTAGE IS THE VREFERENCE OF THE ADC SO 0v TO 5v CORRESPOND TO 0 TO 1023 VALUE GENERATED BY ADC
	THE ACQUIZITION TIME IS NEEDED TO ENSURE THAT THE CAPACITOR FULLY CHARGED BY THE VOLTAGE PRESENT AT THE PIN RA0
	THE CONVERSION CLOCK MUST NOT BE HIGHER THEN 625 KHZ OR LESS THEN 1.6 US
*/
#include <p18f452.h>
#define TRUE 1						// DEFINE TRUE AS 1
#pragma config WDT = OFF
void acquisitionTime(void);			// TIME ACQUIZITION ABOUT 20 US
void affiche(unsigned int value);	// FUNCTION TO DISPLAY THE RESULT IN 7 SEGMENT
void main(void)						// MAIN FUNCTION
{	
	unsigned int oldValue = 0, newValue = 0;	// DECLARING TWO VARIABLES OF TYPE INT 
	TRISAbits.TRISA0 = 1;						// RA0 AS INPUT AS ANALOG PIN
	TRISC = 0x00;								// PORTC OUTPUT
	ADCON0 = 0x43;								// ADCON0 AND ADCON1 FOR CONFIGURING THE ADC MODULE CLOCK CONVERSION FOSC/8, RIGHT JUSTIFIED, VDD AS VREF
	ADCON1 = 0xB0;		
	acquisitionTime();				
	ADCON0bits.GO = 1;							// START CONVERSION
	while(ADCON0bits.DONE == 1);				// MONITOR THE BIT DONE(POLLING)
	oldValue = ADRESH;							// PUT THE LOWEST 2BIT OF ADRESH INTO oldValue REGISTER
	oldValue <<= 8;								// SHIFT THE VALUE LEFT BY 8 POSITIONS
	oldValue += ADRESL;							// ADD THE CONTENT OF ADREL TO OldValue
	affiche(oldValue);							// DISPLAY RESULT INTO PORTC
	while(TRUE)									// STAY HERE
	{
		acquisitionTime();
		ADCON0bits.GO = 1;
		while(ADCON0bits.DONE == 1);	
		newValue = ADRESH;
		newValue <<= 8;
		newValue += ADRESL;
		if(newValue != oldValue)
		{
			affiche(newValue);
			oldValue = newValue;
		}
	}
}
void acquisitionTime(void)
{
	T0CON = 0x48;					// T0CON REGISTER
	TMR0L = 0xEB;					// TIMER0 FOR GENERATING TIME
	INTCONbits.TMR0IF = 0;			// CLEAR THE FLAG
	T0CONbits.TMR0ON = 1;			// START THE TIMER
	while(INTCONbits.TMR0IF == 0);	
	INTCONbits.TMR0IF = 0;
	T0CONbits.TMR0ON = 0;	
}
void affiche(unsigned int value)
{
	unsigned char array[] = {0x3F, 0x06, 0x5B, 0x4F, 0x66, 0x6D, 0x7D, 0x07, 0x7F, 0x6F};	// EACH ELEMENT CORRESPOND TO ITS INDEX(EX : 0x3F == 0, 0x6F == 9)
	unsigned char val = (value*9)/1023;														// THE HIGHEST OUTPUT OF ADC CORRESPOND TO 9
	PORTC = array[val];				// DISPLAY RESULT
}